{"frames":[{"func":"model %>% fit(x = train_input, y = train_output, epochs = 200, \n    validation_split = 0.2, callbacks = callback_early_stopping(patience = 20))","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"fit(., x = train_input, y = train_output, epochs = 200, validation_split = 0.2, \n    callbacks = callback_early_stopping(patience = 20))","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"fit.keras.src.models.model.Model(., x = train_input, y = train_output, \n    epochs = 200, validation_split = 0.2, callbacks = callback_early_stopping(patience = 20))","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"do.call(object$fit, args)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"(structure(function (x = NULL, y = NULL, batch_size = NULL, epochs = 1L, \n    verbose = \"auto\", callbacks = NULL, validation_split = 0, \n    validation_data = NULL, shuffle = TRUE, class_weight = NULL, \n    sample_weight = NULL, initial_epoch = 0L, steps_per_epoch = NULL,  ...","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"error_handler","file":"/Users/michellegiulajan/.virtualenvs/r-tensorflow/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py","line_number":"122","end_line_nubmer":"122","character_number":0.0},{"func":"build","file":"/Users/michellegiulajan/.virtualenvs/r-tensorflow/lib/python3.12/site-packages/keras/src/trainers/compile_utils.py","line_number":"488","end_line_nubmer":"488","character_number":0.0},{"func":"stop(structure(list(message = \"ValueError: When there is only a single output, the `loss_weights` argument must be a Python float. Received instead: loss_weights=[0.2] of type <class 'list'>\\n\\033[90mRun \\033]8;;rstudio:run:reticulate::py_last_error()\\a`reticulate::py_last_error()`\\033]8;;\\a for details.\\033[39m\", \n    call = py_call_impl(callable, call_args$unnamed, call_args$named)), class = c(\"python.builtin.ValueError\", \n\"python.builtin.Exception\", \"python.builtin.BaseException\", \"python.builtin.object\", \n\"error\", \"condition\"), py_object = <environment>))","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0}],"message":"Error in py_call_impl(callable, call_args$unnamed, call_args$named) : \n  ValueError: When there is only a single output, the `loss_weights` argument must be a Python float. Received instead: loss_weights=[0.2] of type <class 'list'>\n\u001B[90mRun \u001B]8;;rstudio:run:reticulate::py_last_error()\u0007`reticulate::py_last_error()`\u001B]8;;\u0007 for details.\u001B[39m\n"}